version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: warehouse-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./initdb.js:/docker-entrypoint-initdb.d/initdb.js:ro

  server:
    build: 
      context: ./warehouse-server
    container_name: warehouse-server
    restart: always
    ports:
      - "5005:5005"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/warehouse
    depends_on:
      - mongodb

  client:
    build:
      context: ./warehouse-app
    container_name: warehouse-client
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongo-data:
